# Linux, which just cooperates well
os: linux
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python --version
install: pip install .[test]
after_success:
  - codecov
script: python -m pytest --cov=ebmlite

matrix:
  include:

    # Windows, which does not cooperate well

    - os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version=3.7.4
        - python --version
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - pip install .[test]

