# Linux, which just cooperates well
os: linux
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install .
script: python -m pytest

matrix:
  include:

    # Windows, which does not cooperate well

    - os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - choco install python --version=3.7.4
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - pip install pytest numpy

