[tool]
  [tool.pylint]
    [tool.pylint.master]
      fail-under=10
    [tool.pylint.messages_control]
      disable="all"
      enable=[
        "async",
        "format",
        "invalid-name",  # basic
        "imports",
        "miscellaneous",
        "refactoring",
        "similarities",
        "stdlib",
        "string",
        ]
    [tool.pylint.reports]
    [tool.pylint.format]
      indent-string="    "
      indent-after-paren=8
    [tool.pylint.logging]
    [tool.pylint.miscelaneous]
      notes=[
        "TODO",
        "HACK",
        "XXX",
      ]
    [tool.pylint.spelling]
    [tool.pylint.string]
    [tool.pylint.typecheck]
    [tool.pylint.basic]
      good-names=[
        "i",
        "j",
        "k",
        "t",
        "x",
        "y",
        "z",
        "ex",
        "Run",
        "_",
        "__"
      ]
      # Naming Conventions
      argument_naming-style="camelCase"
      attr-naming-style="camelCase"
      class-naming-style="PascalCase"
      class-attribute-naming-style="UPPER_CASE"
      const-naming-style="UPPER_CASE"
      function-naming-style="camelCase"
      inlinevar-naming-style="camelCase"
      method-naming-style="camelCase"
      module-naming-style="snake_case"
      variable-naming-style="camelCase"
  [tool.pytest]
    [tool.pytest.ini_options]
      required_plugins=["pytest-cov"]
      testpaths=[""]