from typing import Any, Dict, List, Union

SCHEMA_PATH: List[str] = ...
SCHEMATA: Dict[Union[str, bytes, bytearray], Any] = ...


class Element:
    dtype: Any = ...
    def parse(self, stream: BinaryIO, size: int) -> Any: ...
    def __init__(self,
                 stream = ...,
                 offset: int = ...,
                 size: int = ...,
                 payloadOffset: int = ...): ...
    def __eq__(self, other: Any) -> bool: ...