name: Unit test on push and PR


on: [push, pull_request, workflow_dispatch]


jobs:
  unit-tests:
    name: Run Unit Tests

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']

    env:
      OS: ${{ matrix.os }}
      PYTHON-VERSION: ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip

      - uses: actions/checkout@v4

      - run: python -m pip install .[test]

      - run: python -m pytest ./tests/ --cov=ebmlite --cov-report=xml -n auto

#      - uses: actions/upload-artifact@v4
#        with:
#          name: multi-file-stuff
#          overwrite: true
#          path: |
#            ./tests/SSX46714-doesnot.IDE
#            ./tests/SSX46714-new.IDE
#            ./tests/ssx-1.xml
#            ./tests/ssx-2.xml

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON-VERSION
          files: ./coverage.xml
          name: ${{ matrix.os }} ${{ matrix.python-version }}
          verbose: true
